name: Maven Build and Test

on:
  push:
    branches: [ "main" ] # Specify the branches that trigger the workflow

jobs:
  build:

    runs-on: windows-latest # Select the runner environment (e.g., Ubuntu, Windows)

    steps:
      - uses: actions/checkout@v3 # Check out the code from the repository

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: |
          mvn clean install

      - name: Run Tests
        run: |
          mvn test